<a href="https://colab.research.google.com/github/UVDivyaSree/PW_Skills_Assignments/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.create a 3*3 numPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
array

array([[35, 42, 31],
       [46, 16, 29],
       [ 6, 23, 74]])

In [4]:
# Interchange its rows and columns (transpose)
transposed_array = array.T

print("Original Array:")
print(array)
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[35 42 31]
 [46 16 29]
 [ 6 23 74]]

Transposed Array:
[[35 46  6]
 [42 16 23]
 [31 29 74]]


#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array


In [6]:
import numpy as np
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
array_2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
array_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [15]:
import numpy as np
#4x4 NumPy array with random float values.
array = np.random.rand(4,4)
array

array([[0.06350327, 0.90590246, 0.78765414, 0.63664062],
       [0.61871512, 0.81616993, 0.66925052, 0.57008865],
       [0.77237715, 0.06310413, 0.02225446, 0.01600534],
       [0.87255421, 0.44958877, 0.43087412, 0.27663889]])

In [18]:
# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array_6x6

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.06350327, 0.90590246, 0.78765414, 0.63664062,
        0.        ],
       [0.        , 0.61871512, 0.81616993, 0.66925052, 0.57008865,
        0.        ],
       [0.        , 0.77237715, 0.06310413, 0.02225446, 0.01600534,
        0.        ],
       [0.        , 0.87255421, 0.44958877, 0.43087412, 0.27663889,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
"""The np.pad function adds extra space around your array. In this case:

pad_width=1: It adds 1 row of padding on the top and bottom, and 1 column on the left and right, making the array bigger.
mode='constant' and constant_values=0: It fills the padding with zeros.
So, if your original array is 4x4, np.pad makes it a 6x6 array by adding a "border" of zeros around it."""


#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [21]:
import numpy as np
# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 60, 5)
array
#in above case if we give 60 it will be excluded and give values upto 59
#if we give 61 then 61 will excluded and give values upto 60
#10-included-start , 60-excluded-stop , 5-step-difference value

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

#5.5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [22]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original Array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)
print("Capitalized:", capitalize_array)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalized: ['Python' 'Numpy' 'Pandas']


#6.Generate a NumPy array of words. Insert a space between each character of every word  in the array.

In [23]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original Array:", words_array)
print("Spaced Characters Array:", spaced_words_array)


Original Array: ['hello' 'world' 'numpy' 'array']
Spaced Characters Array: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [24]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [25]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [27]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers Array:\n", random_integers)
print("\nPrime Numbers in the Array:", prime_numbers)


Random Integers Array:
 [656 665 300 306 534  17 174 196  55 986 447 990 416 616 721 726 338 607
 221 376 630 899 831 339 804 897 795 326 971 665   8 261 324 663 219 240
  77 582 380 417 595 935 849 600 144 924 343 530 981 152 808 846 198 889
 236 206 331 693 706 409 837 216 487  16 824 541 861 346  40 782 857 126
 541 997 457 922 360 508 154 826 516 416 491 466 993 232 128 991 389 733
 400 401 753 699 800 786 223 749 800 709]

Prime Numbers in the Array: [17, 607, 971, 331, 409, 487, 541, 857, 541, 997, 457, 491, 991, 389, 733, 401, 223, 709]


#10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [30]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's use random temperatures between 25 and 45 degrees Celsius
daily_temperatures = np.random.randint(25, 46, size=30)

# Calculate weekly averages
# We have 4 full weeks and 2 extra days
weeks = daily_temperatures[:28].reshape(4, 7)  # First 28 days
remaining_days = daily_temperatures[28:]  # Last 2 days

# Calculate weekly averages for the full weeks
weekly_averages = np.mean(weeks, axis=1)

# Calculate average for the last 2 days (or you can choose to include them as a separate week)
remaining_average = np.mean(remaining_days) if len(remaining_days) > 0 else 0

print("Daily Temperatures for the Month (30 days):\n", daily_temperatures)
print("\nWeekly Averages for the First 4 Weeks:\n", weekly_averages)
print("\nAverage for Remaining Days:\n", remaining_average)


Daily Temperatures for the Month (30 days):
 [25 33 35 31 25 28 44 34 41 35 31 35 42 37 39 39 39 36 42 34 44 41 45 38
 35 35 43 31 27 42]

Weekly Averages for the First 4 Weeks:
 [31.57142857 36.42857143 39.         38.28571429]

Average for Remaining Days:
 34.5


Explanation:

daily_temperatures[:28].reshape(4, 7): This takes the first 28 days and reshapes them into a 4x7 array.

remaining_days = daily_temperatures[28:]: This captures the last 2 days of temperatures.

Calculating averages: The average is calculated for the first four weeks, and the average for the remaining two days is calculated separately.

Running this code will display the daily temperatures for the month, the weekly averages for the first four weeks, and the average for the remaining days.









